sudo: required
dist: xenial

language: cpp

compiler:
  - gcc

services:
  - docker

script:
  - ./mcrouter/scripts/install_ubuntu_16.04.sh "$(pwd)"/mcrouter-install
  - docker build -t facebook/mcrouter .

notifications:
  email:
    - mcrouter@fb.com
